name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --deploy
      - name: Check code formatting
        run: pipenv run fmt-check
      - name: Lint
        run: pipenv run lint
      - name: Test
        run: pipenv run test
